/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vista;

import com.controlador.modelo.ControladorCargo;
import com.modelo.Cargo;
import com.modelo.Contrato;
import com.modelo.Empresa;
import com.modelo.Trabajador;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author EstAngelMesiasJadanC
 */
public class VistaContratosTrabajador extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaContratosTrabajdor
     */
    private Empresa empreesa;
    private Trabajador trabajador;
    Cargo cargo = new Cargo();
    ControladorCargo cCargo = new ControladorCargo();

    public VistaContratosTrabajador(Empresa empresa, Trabajador trabajador) {
        initComponents();
        this.empreesa = empresa;
        this.trabajador = trabajador;
        lblidentificacion.setText(trabajador.getIdentificacion());
        lbltrabajador.setText(trabajador.getNombre() + " " + trabajador.getAplellido());
        lblempresa.setText(empresa.getRazonSocial());
        listarContratos();
    }

    private void listarContratos() {
        for (Cargo cargo1 : cCargo.listarCargo()) {
            cboxcargo.addItem(cargo1.getCargo());
        }
    }

    private void buscarSueldo() {
        String cargo = cboxcargo.getSelectedItem().toString();
        Cargo car = new Cargo();
        car = cCargo.buscarCargo(cargo);
        txtsueldo.setText(String.valueOf(car.getSueldo()));
    }

    private int validarCampos() {
        int estado = 0;
        if (jcheckjcompleta.isSelected() == false && jcheckjparcial.isSelected() == false) {
            jcheckjcompleta.setForeground(Color.red);
            jcheckjparcial.setForeground(Color.red);
            JOptionPane.showMessageDialog(this, "Debe elegir un tipo de jornada");
        } else {
            jcheckjcompleta.setForeground(Color.black);
            jcheckjparcial.setForeground(Color.black);
            estado++;
        }
        if ((cboxtcontrato.getSelectedItem().toString()) == "Seleccionar") {
            JOptionPane.showMessageDialog(this, "Seleccione un tipo de contrato");
            cboxtcontrato.setForeground(Color.red);
            estado++;
        } else {
            cboxtcontrato.setForeground(Color.black);
        }
        if ((cboxcargo.getSelectedItem().toString()) == "Seleccionar") {
            JOptionPane.showMessageDialog(this, "Seleccione un cargo de trabajo");
            cboxcargo.setForeground(Color.red);
        } else {
            cboxcargo.setForeground(Color.black);
            estado++;
        }
        if ((cboxrelacionLaboral.getSelectedItem().toString()) == "Seleccionar") {
            JOptionPane.showMessageDialog(this, "Seleccione una relacion laboral.");
            cboxrelacionLaboral.setForeground(Color.red);
        } else {
            cboxrelacionLaboral.setForeground(Color.black);
            estado++;
        }
        if (Double.parseDouble(txtsueldo.getText()) <= 0) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un sueldo.");
            txtsueldo.setForeground(Color.red);
        } else {
            txtsueldo.setForeground(Color.black);
            estado++;
        }
        return estado;
    }

    private Contrato obenerDatos() {
        int jornada = 0;
        String fInicio = "";
        String tContrato = "";
        String rLaboral = "";
        String cargo = "";
        double sueldo = 0.00;
        boolean prueba = false;

        Contrato contra = new Contrato();
        if (jcheckjcompleta.isSelected()) {
            jornada = 1;
        }
        if (jcheckjparcial.isSelected()) {
            jornada = 2;
        }
        fInicio = date.getText();
        tContrato = cboxtcontrato.getSelectedItem().toString();
        rLaboral = cboxrelacionLaboral.getSelectedItem().toString();
        cargo = cboxcargo.getSelectedItem().toString();
        sueldo = Double.parseDouble(txtsueldo.getText());
        prueba = jcheckperidoPrueba.isSelected();

        contra.setJornada(jornada);
        contra.setFechaIngreso(fInicio);
        contra.setRelacionLaboral(rLaboral);
        contra.setCargo(cargo);
        contra.setSueldo(sueldo);
        contra.setPeriodoPrueba(prueba);
        contra.setTrabajador(trabajador);
        contra.setEmpresa(empreesa);
        return contra;
    }

    private void guardarContrato() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbltipoid = new javax.swing.JLabel();
        lbltrabajador = new javax.swing.JLabel();
        lblidentificacion = new javax.swing.JLabel();
        btnjornada = new javax.swing.JButton();
        jcheckjcompleta = new javax.swing.JCheckBox();
        jcheckjparcial = new javax.swing.JCheckBox();
        lblempresa = new javax.swing.JLabel();
        cboxtcontrato = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        date = new datechooser.beans.DateChooserCombo();
        jLabel2 = new javax.swing.JLabel();
        cboxcargo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtsueldo = new javax.swing.JTextField();
        jcheckperidoPrueba = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        cboxrelacionLaboral = new javax.swing.JComboBox<>();
        btnguardar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblhorario = new javax.swing.JLabel();

        setClosable(true);
        setResizable(true);

        jLabel1.setText("Trabajador");

        lbltipoid.setText("Cedula");

        lbltrabajador.setText("jLabel2");

        lblidentificacion.setText("jLabel2");

        btnjornada.setText("Componer jornada");
        btnjornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjornadaActionPerformed(evt);
            }
        });

        jcheckjcompleta.setText("Jornada Completa");
        jcheckjcompleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcheckjcompletaActionPerformed(evt);
            }
        });

        jcheckjparcial.setText("Jornada Parcial");
        jcheckjparcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcheckjparcialActionPerformed(evt);
            }
        });

        lblempresa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblempresa.setText("jLabel2");

        cboxtcontrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Indefinido", "A tiempo parcial", "Servicio Domestico" }));
        cboxtcontrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxtcontratoActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo de contrato");

        jLabel4.setText("Inicio laboral");

        jLabel2.setText("Cargo");

        cboxcargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        cboxcargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxcargoActionPerformed(evt);
            }
        });

        jLabel6.setText("Sueldo");

        txtsueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsueldoActionPerformed(evt);
            }
        });

        jcheckperidoPrueba.setText("Periodo de prueba");

        jLabel9.setText("Relacion laboral");

        cboxrelacionLaboral.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Tiempo Completo", "A tiempo parcial" }));

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnactualizar.setText("Actualizar");

        jButton1.setText("Registrar cargo");

        lblhorario.setText("Sin horario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbltipoid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbltrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                                .addComponent(lblempresa, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblidentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(btnjornada)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblhorario, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jcheckjcompleta)
                                    .addGap(18, 18, 18)
                                    .addComponent(jcheckjparcial))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnguardar)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnactualizar))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel3))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cboxtcontrato, 0, 309, Short.MAX_VALUE)
                                                .addComponent(cboxrelacionLaboral, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboxcargo, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcheckperidoPrueba))))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lbltrabajador)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblempresa)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltipoid)
                    .addComponent(lblidentificacion))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcheckjparcial)
                    .addComponent(jcheckjcompleta))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnjornada)
                    .addComponent(lblhorario))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxtcontrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cboxrelacionLaboral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxcargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcheckperidoPrueba)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar)
                    .addComponent(btnactualizar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnjornadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjornadaActionPerformed
        // TODO add your handling code here:

        String jornada="";
        if (jcheckjcompleta.isSelected()) {
            jornada="Jornada Completa";
        }if (jcheckjparcial.isSelected()) {
            jornada="Jornada Parcial";
        }
        if (jornada!="") {
            VistaHorario vhorario = new VistaHorario(empreesa, jornada);
            VistaInicio.jpaneldesktop.add(vhorario);
            vhorario.toFront();
            vhorario.setVisible(true);
        }else{
            JOptionPane.showConfirmDialog(this,"Primero debe elegir un tipo de jornada");
            jcheckjcompleta.setForeground(Color.red);
            jcheckjparcial.setForeground(Color.red);
        }
        
    }//GEN-LAST:event_btnjornadaActionPerformed

    private void txtsueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsueldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsueldoActionPerformed

    private void cboxtcontratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxtcontratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxtcontratoActionPerformed

    private void cboxcargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxcargoActionPerformed
        // TODO add your handling code here:
        buscarSueldo();
    }//GEN-LAST:event_cboxcargoActionPerformed

    private void jcheckjcompletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheckjcompletaActionPerformed
        // TODO add your handling code here:
        jcheckjcompleta.setForeground(Color.black);
        jcheckjparcial.setForeground(Color.black);
        if (jcheckjcompleta.isSelected()) {
            jcheckjparcial.setSelected(false);
        }
    }//GEN-LAST:event_jcheckjcompletaActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        int es = validarCampos();
        System.out.println(es);
    }//GEN-LAST:event_btnguardarActionPerformed

    private void jcheckjparcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheckjparcialActionPerformed
        // TODO add your handling code here:
        jcheckjcompleta.setForeground(Color.black);
        jcheckjparcial.setForeground(Color.black);
        if (jcheckjparcial.isSelected()) {
            jcheckjcompleta.setSelected(false);
        }
    }//GEN-LAST:event_jcheckjparcialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnjornada;
    private javax.swing.JComboBox<String> cboxcargo;
    private javax.swing.JComboBox<String> cboxrelacionLaboral;
    private javax.swing.JComboBox<String> cboxtcontrato;
    private datechooser.beans.DateChooserCombo date;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jcheckjcompleta;
    private javax.swing.JCheckBox jcheckjparcial;
    private javax.swing.JCheckBox jcheckperidoPrueba;
    private javax.swing.JLabel lblempresa;
    private javax.swing.JLabel lblhorario;
    private javax.swing.JLabel lblidentificacion;
    private javax.swing.JLabel lbltipoid;
    private javax.swing.JLabel lbltrabajador;
    private javax.swing.JTextField txtsueldo;
    // End of variables declaration//GEN-END:variables
}
