/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vista;

import com.controlador.modelo.ControladorTrabajador;
import com.modelo.Empresa;
import com.modelo.Trabajador;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author EstAngelMesiasJadanC
 */
public class VistaTrabajador extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaTrabajador
     */
    private Empresa empresa;
    Trabajador trabajador = new Trabajador();
    ControladorTrabajador ctrabaTrabajador = new ControladorTrabajador();
    
    public VistaTrabajador(Empresa empresa) {
        initComponents();
        this.empresa = empresa;
        lblempresa.setText(empresa.getRazonSocial());
        //AutoCompleteDecorator.decorate(cboxidentificacion);

        btnguardar.setVisible(false);
        btnactualizar.setVisible(false);
        btneliminar.setVisible(false);
        btnacargas.setVisible(false);
        btngencontrato.setVisible(false);
        btneditar.setVisible(false);
        deshabTextos();
    }
    private void vaciarCampos(){
        cboxtiipoid.setSelectedItem("Seleccionar");
        txtidentificacion.setText("");
        txtnombre.setText("");
        txtapellido.setText("");
        txttelefono.setText("");
        txtdireccion.setText("");
        txtcorreo.setText("");
    }
    
    private void validarCedula(String cedula) {
        boolean estado = false;
        estado = trabajador.validaCedula(cedula);
        if (estado == false) {
            JOptionPane.showMessageDialog(this, "El numero de cedula es invalido, revise porfavor");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboxtiipoid = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnacargas = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        date = new datechooser.beans.DateChooserCombo();
        lblempresa = new javax.swing.JLabel();
        btngencontrato = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        txtidentificacion = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btnnuevo = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);

        jpanel.setBackground(new java.awt.Color(255, 255, 255));
        jpanel.setAutoscrolls(true);

        jButton5.setText("Buscar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 153));
        jLabel15.setText("Datos Personales");

        jLabel4.setText("Tipo Identificacion");

        cboxtiipoid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Pasaporte", "Cedula" }));
        cboxtiipoid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxtiipoidActionPerformed(evt);
            }
        });

        jLabel5.setText("Identificacion");

        jLabel1.setText("Nombres");

        jLabel2.setText("Apellidos");

        jLabel6.setText("Fecha de Nacimiento");

        jLabel12.setText("Telfono");

        jLabel13.setText("Correo");

        txtdireccion.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        txtdireccion.setDragEnabled(true);

        jLabel14.setText("Direccion");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Tipo Id", "Identificacion", "Nombres", "Apellidos", "Parentesco", "Fecha de Nacimiento"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnacargas.setText("Agregar Carga");
        btnacargas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnacargasActionPerformed(evt);
            }
        });

        jLabel3.setText("Cargas familiares del trabajador");

        date.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 16),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 16),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 16),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 16),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 16),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 16),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    date.setEnabled(false);

    lblempresa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    lblempresa.setText("jLabel7");

    btngencontrato.setText("Generar contrato");
    btngencontrato.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btngencontratoActionPerformed(evt);
        }
    });

    jTable3.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "N", "Fecha inicio", "Tipo Contrato", "Relacion Laboral", "Cargo", "Sueldo", "Prueba"
        }
    ));
    jScrollPane2.setViewportView(jTable3);
    if (jTable3.getColumnModel().getColumnCount() > 0) {
        jTable3.getColumnModel().getColumn(0).setMinWidth(5);
        jTable3.getColumnModel().getColumn(0).setPreferredWidth(5);
        jTable3.getColumnModel().getColumn(6).setMinWidth(5);
        jTable3.getColumnModel().getColumn(6).setPreferredWidth(5);
    }

    txtidentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            txtidentificacionKeyReleased(evt);
        }
    });

    jLabel7.setText("Contratos registrados");

    jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

    btnnuevo.setText("Nuevo");
    btnnuevo.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnnuevoActionPerformed(evt);
        }
    });

    btneditar.setText("Editar");
    btneditar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btneditarActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jpanelLayout = new javax.swing.GroupLayout(jpanel);
    jpanel.setLayout(jpanelLayout);
    jpanelLayout.setHorizontalGroup(
        jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jpanelLayout.createSequentialGroup()
            .addGap(25, 25, 25)
            .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpanelLayout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4))
                    .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpanelLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jpanelLayout.createSequentialGroup()
                                    .addComponent(txtidentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton5)
                                    .addGap(11, 11, 11))
                                .addComponent(txtnombre)
                                .addComponent(txtapellido, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelLayout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(cboxtiipoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btneliminar)
                                .addComponent(lblempresa, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addComponent(jLabel15)
                .addGroup(jpanelLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
                        .addComponent(jScrollPane2)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelLayout.createSequentialGroup()
                            .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addGroup(jpanelLayout.createSequentialGroup()
                                    .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel6)
                                        .addComponent(btnacargas)
                                        .addGroup(jpanelLayout.createSequentialGroup()
                                            .addComponent(btnnuevo)
                                            .addGap(44, 44, 44)))
                                    .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jpanelLayout.createSequentialGroup()
                                            .addGap(15, 15, 15)
                                            .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(txttelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(date, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpanelLayout.createSequentialGroup()
                                                        .addComponent(btnguardar)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(txtdireccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                                    .addComponent(txtcorreo, javax.swing.GroupLayout.Alignment.LEADING))))
                                        .addGroup(jpanelLayout.createSequentialGroup()
                                            .addGap(60, 60, 60)
                                            .addComponent(btngencontrato))))
                                .addComponent(jLabel3))
                            .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jpanelLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                    .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator3)
                                        .addGroup(jpanelLayout.createSequentialGroup()
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(432, 432, 432))))
                                .addGroup(jpanelLayout.createSequentialGroup()
                                    .addGap(80, 80, 80)
                                    .addComponent(btnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 316, Short.MAX_VALUE)))))))
            .addContainerGap())
        .addGroup(jpanelLayout.createSequentialGroup()
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );
    jpanelLayout.setVerticalGroup(
        jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel15)
            .addGap(18, 18, 18)
            .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(cboxtiipoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblempresa))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(txtidentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton5))
            .addGap(7, 7, 7)
            .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(9, 9, 9)
            .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(12, 12, 12)
            .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel6)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel12)
                .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel13)
                .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel14)
                .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnnuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnguardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btneditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(18, 18, 18)
            .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpanelLayout.createSequentialGroup()
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btngencontrato)
                        .addComponent(btnacargas)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(1, 1, 1)
            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(14, 14, 14)
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel7)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(0, 0, 0)
            .addComponent(jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(20, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnacargasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnacargasActionPerformed
        // TODO add your handling code here:
        if (trabajador.getIdentificacion() != null) {
            VistaCargas vistaCargas = new VistaCargas(empresa, trabajador);
            VistaInicio.jpaneldesktop.add(vistaCargas);
            vistaCargas.toFront();
            vistaCargas.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Debe ingresar primero los datos del trabajador");
        }
    }//GEN-LAST:event_btnacargasActionPerformed
    
    public void guardarTrabajador() {
        String tipoId = cboxtiipoid.getSelectedItem().toString();
        String identificacion = txtidentificacion.getText();
        String nombre = txtnombre.getText();
        String apellido = txtapellido.getText();
        String fNacimiento = date.getText();
        String telefono = txttelefono.getText();
        String correo = txtcorreo.getText();
        String direccion = txtdireccion.getText();
        
        trabajador.setTipoIdentificacion(tipoId);
        trabajador.setIdentificacion(identificacion);
        trabajador.setNombre(nombre);
        trabajador.setAplellido(apellido);
        trabajador.setFechaDeNacimiento(fNacimiento);
        trabajador.setTelefono(telefono);
        trabajador.setCorreoElectronico(correo);
        trabajador.setDireccion(direccion);
        
        boolean validado = validarCampos();
        if (validado == true) {
            boolean estado = ctrabaTrabajador.crearTrabajador(trabajador, empresa.getCodigo());
            if (estado == true) {
                JOptionPane.showMessageDialog(this, "Los el trabajador ha sido guardado");
                deshabTextos();
            } else {
                JOptionPane.showMessageDialog(this, "No se ha podido guardar el trabajador, revise por favor");
            }
        }
    }
    
    public void deshabTextos() {
        
        txtnombre.setEnabled(false);
        txtapellido.setEnabled(false);
        txttelefono.setEnabled(false);
        txtcorreo.setEnabled(false);
        txtdireccion.setEnabled(false);
        date.setEnabled(false);
    }
    
    public boolean validarCampos() {
        boolean estado = false;
        if (txtidentificacion.getText() == null
                || txtnombre.getText() == null || txtapellido.getText() == null
                || txttelefono.getText() == null || txtcorreo.getText() == null
                || txtdireccion.getText() == null) {
            JOptionPane.showMessageDialog(this, "Debe llenar todos los campos");
            estado = false;
        } else {
            estado = true;
        }
        return estado;
    }
    
    public void buscarTrabajador() {
        String id = txtidentificacion.getText();
        trabajador = ctrabaTrabajador.buscarTrabajador(id, "", empresa.getCodigo());
        
        if (trabajador.getIdentificacion() != null) {
            cboxtiipoid.setSelectedItem(trabajador.getTipoIdentificacion());
            txtnombre.setText(trabajador.getNombre());
            txtapellido.setText(trabajador.getAplellido());
            date.setText(trabajador.getFechaDeNacimiento());
            txtcorreo.setText(trabajador.getCorreoElectronico());
            txttelefono.setText(trabajador.getTelefono());
            txtdireccion.setText(trabajador.getDireccion());
            deshabTextos();
            btneliminar.setVisible(true);
            btnacargas.setVisible(true);
            btngencontrato.setVisible(true);
        } else if (trabajador.getIdentificacion() == null) {
            JOptionPane.showMessageDialog(this, "El trabajador no se ha encontrado");
            btneditar.setVisible(false);
            btneliminar.setVisible(false);
            btnacargas.setVisible(false);
            btngencontrato.setVisible(false);
        }
    }
    
    private void habCampost() {
        txtidentificacion.setEnabled(true);
        txtnombre.setEnabled(true);
        txtapellido.setEnabled(true);
        txttelefono.setEnabled(true);
        txtcorreo.setEnabled(true);
        txtdireccion.setEnabled(true);
        date.setEnabled(true);
    }
    private void btngencontratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngencontratoActionPerformed
        // TODO add your handling code here:
        String iden = txtidentificacion.getText();
        if (trabajador.getIdentificacion() != null) {
            VistaContratosTrabajador vct = new VistaContratosTrabajador(empresa, trabajador);
            VistaInicio.jpaneldesktop.add(vct);
            vct.toFront();
            vct.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Debe ingresar primero los datos del trabajador");
        }
    }//GEN-LAST:event_btngencontratoActionPerformed

    private void cboxtiipoidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxtiipoidActionPerformed
        // TODO add your handling code here:
        try {
            String cedula = txtidentificacion.getText();
            String tipoCedula = cboxtiipoid.getSelectedItem().toString();
            if (cedula.length() == 10 && tipoCedula == "Cedula") {
                validarCedula(cedula);
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_cboxtiipoidActionPerformed

    private void txtidentificacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidentificacionKeyReleased
        // TODO add your handling code here:

        try {
            if (evt.getKeyCode() != 10) {
                String cedula = txtidentificacion.getText();
                String tipoCedula = cboxtiipoid.getSelectedItem().toString();
                if (cedula.length() > 10 && tipoCedula == "Cedula") {
                    JOptionPane.showMessageDialog(this, "El numero de cedula no debe tener mas de 10 caracteres");
                } else {
                    if (cedula.length() == 10 && tipoCedula == "Cedula") {
                        validarCedula(cedula);
                    }
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtidentificacionKeyReleased

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        guardarTrabajador();
    }//GEN-LAST:event_btnguardarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if ((txtidentificacion.getText()).length() != 0) {
            buscarTrabajador();
            btneliminar.setVisible(true);
            btneditar.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Debe llenar el numero de identificacion del trabajador");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        // TODO add your handling code here:
        btneditar.setVisible(false);
        btnactualizar.setVisible(true);
        habCampost();
    }//GEN-LAST:event_btneditarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
        btnnuevo.setEnabled(true);
        txtidentificacion.setEnabled(true);
        txtnombre.setEnabled(true);
        txtapellido.setEnabled(true);
        txttelefono.setEnabled(true);
        txtdireccion.setEnabled(true);
        txtcorreo.setEnabled(true);
        habCampost();
        vaciarCampos();
        btnguardar.setVisible(true);
        btnnuevo.setVisible(false);
    }//GEN-LAST:event_btnnuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnacargas;
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btngencontrato;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JComboBox<String> cboxtiipoid;
    private datechooser.beans.DateChooserCombo date;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JPanel jpanel;
    private javax.swing.JLabel lblempresa;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtidentificacion;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
