/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Angel
 */
public class Caras extends javax.swing.JPanel {

    /**
     * Creates new form Caras
     */
    public Caras() {
        initComponents();
    }

    
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        
        //Dibujo la cara 
        g.setColor(Color.YELLOW);
        g.fillOval(210, 110, 190, 200);
        
        //Cebello
        g.setColor(Color.BLACK);
        g.fillOval(220, 118, 40, 30);
        g.fillOval(250, 115, 40, 30);
        g.fillOval(280, 115, 40, 30);
        g.fillOval(310, 115, 40, 30);
        g.fillOval(340, 115, 40, 30);
        g.fillOval(370, 118, 20, 30);
        
        g.fillOval(230, 108, 100, 40);
        g.fillOval(270, 108, 100, 40);
        
        //Cejas
        g.setColor(Color.BLACK);
        g.fillOval(245, 160, 30, 20);
        g.fillOval(330, 160, 30, 20);
        g.setColor(Color.YELLOW);
        g.fillOval(245, 163, 30, 20);
        g.fillOval(330, 163, 30, 20);

        //Dibujo los ojos 
        g.setColor(Color.BLACK);
        g.fillOval(245, 165, 30, 30);
        g.fillOval(330, 165, 30, 30);
        
        //Orejas
        g.setColor(Color.YELLOW);
        g.fillOval(383, 160, 20, 30);
        g.fillOval(205, 160, 20, 30);
        
        //Naris
        g.setColor(Color.ORANGE);
        g.fillOval(294, 185, 20, 15);
               
        
    }

    
    public void feliz(Graphics g) {
        super.paint(g);
        
        //Dibujo la boca
        g.setColor(Color.BLACK);
        g.fillOval(250, 210, 120, 60);
        
        //Dientes
        g.setColor(Color.WHITE);
        g.fillRect(255, 210, 110, 40);

        //Convierto la boca en una sonrisa
        g.setColor(Color.YELLOW);
        g.fillRect(250, 210, 120, 35);
                        
    }
    public void triste(Graphics g) {
        super.paint(g);
        
        //Dibujo la boca
        g.setColor(Color.BLACK);
        g.fillRect(275, 250, 60, 10);
        g.setColor(Color.WHITE);
        g.fillRect(280, 250, 50, 5);
        
    }
    
    public void asombrado(Graphics g) {
        super.paint(g);
        g.setColor(Color.BLACK);
        g.fillOval(290, 250, 20, 50);
        
        //Dientes superior
        g.setColor(Color.WHITE);
        g.fillOval(293, 250, 5, 10);
        g.fillOval(296, 250, 5, 10);
        g.fillOval(298, 250, 5, 10);
        g.fillOval(300, 250, 5, 10);
        g.fillOval(303, 253, 5, 7);
        
        //Dientes inferior
        
        g.setColor(Color.WHITE);
        g.fillOval(292, 288, 5, 8);
        g.fillOval(294, 289, 5, 9);
        g.fillOval(296, 290, 5, 10);
        g.fillOval(298, 290, 5, 10);
        g.fillOval(300, 290, 5, 10);
        g.fillOval(302, 288, 5, 8);
        

       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setAlignmentX(100.0F);
        setAlignmentY(100.0F);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
